using System.ComponentModel.DataAnnotations;

namespace RestaurantReservation.Models
{
    public class Announcement : IAutoGeneratedId
    {
        [Key]
        [Required(ErrorMessage = "Announcement ID is required.")]
        public string Id { get; set; } = string.Empty;

        [Required]
        public bool IsActive { get; set; }

        [Required(ErrorMessage = "Title is required.")]
        [StringLength(100, ErrorMessage = "Title cannot exceed 100 characters.")]
        public string Title { get; set; } = string.Empty;

        [Required(ErrorMessage = "Description is required.")]
        [StringLength(1000, ErrorMessage = "Description cannot exceed 1000 characters.")]
        public string Description { get; set; } = string.Empty;

        [Required]
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        public DateTime? ExpiresAt { get; set; }
    }
}