using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RestaurantReservation.Models
{
    public enum OrderStatus
    {
        InQueue,
        Preparing,
        Served,
        Completed,
        Cancelled
    }

    public class Order : IAutoGeneratedId
    {
        [Key]
        [Required(ErrorMessage = "Order ID is required.")]
        public string Id { get; set; } = string.Empty;

        [Required]
        [Range(0, 10000000, ErrorMessage = "Total amount must be positive.")]
        public int TotalAmount { get; set; }

        [NotMapped]
        public decimal TotalAmountInMainUnit => TotalAmount / 100m;

        [Required]
        public OrderStatus Status { get; set; } = OrderStatus.InQueue;

        [Required]
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        public DateTime? ServedAt { get; set; }

        // Foreign Keys
        [Required]
        public string SessionId { get; set; } = string.Empty;

        [ForeignKey(nameof(SessionId))]
        public Session? Session { get; set; }

        [Required]
        public string CustomerId { get; set; } = string.Empty;

        [ForeignKey(nameof(CustomerId))]
        public Customer? Customer { get; set; }
    }
}